name: st
favicon: null
layout_spectrum: 0.25292
typography_spectrum: 0.74207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e271d'
    - '#615f53'
    - '#b6c5e6'
    - '#e39d83'
    - '#feeceb'
  brandStrength: 0.40814307425171137
  lightness: 0.09288134216330945
  saturation: 0.314598023891449
  rhythmicContrast: 0.5372639503329992
purpose: []
